services:
  - type: web
    name: fse-terabox
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: TERABOX_CLIENT_ID
        sync: false
      - key: TERABOX_CLIENT_SECRET
        sync: false
      - key: TERABOX_PRIVATE_SECRET
        sync: false
